### ISSUE TITLE
What is password?

### ISSUE THREAD

**Issue by DonMonro** [slooi/kaggle-ssh#1]
when i try connect to ssh in my CMD in windows and past codes on that 
ask me for yes/no/fingerprint
i type yes
its ok and connect but ask me password !!!
what password? where is password?

C:\Users\Administrator>) > ___KAGGLE_PRIVATE_SSH_KEY___
C:\Users\Administrator>ssh -i ___KAGGLE_PRIVATE_SSH_KEY___ root@4.tcp.us-cal-1.ngrok.io -p 16911 -o ServerAliveInterval=60
Warning: Identity file ___KAGGLE_PRIVATE_SSH_KEY___ not accessible: No such file or directory.
Warning: Permanently added the ECDSA host key for IP address '[52.8.11.142]:16911' to the list of known hosts.
root@4.tcp.us-cal-1.ngrok.io's password:

**Comment by slooi** [comment]
Make sure to run the entire script. Not just the line with the `ssh`. The script you run in your local terminal should look like this:
```bash
(
echo -----BEGIN OPENSSH PRIVATE KEY-----
echo b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
echo NhAAAAAwEAAQAAAYEA3iNkBjv+iCxp156Ad8GxYbtjX9ngfENhpzYDXPbPo/OT6KHtmMRc
echo XDi833z4Ps1DR0i2UMJKJ8IpDuwDsK8ar852EixTnrBkF9uTQFQ5+KHlRCceb90SGBEUeb
echo rj9BfQoz9LIOz6KbC8ivTnIkk0iMJocEwRbZQyavh25v/Wq+pcq1XUi2r+2xkrGQMlOEu8
echo X5DefvjmhUZz+Z38Bq3pRHl7VoGmfqoWibVI16MRUVgC745V8nniEnkfBg2mhud6sRGpz0
echo G2Mc7LInDgDlj3rwwNKTfgsw67AxXyZK1DXkFlnUMhxmNpRNzAyxFCcFXVsoVncl4HyEzY
echo bgd9uTLurBqjwMCi5S97UMQ8Odu15d57EEX+OYFAx1+tQ2GD8P11mTVRu7qnCMx6PnVJn4
echo QfxdXLgyO/yTCa4wyWOw2+0OMnJjSEljLB48oz+31NT1v+LcESQ2VGdN+O6iSr2XWM+k9i
echo LmZI31zQpN3noOAmbLxdIHfHoVvNMIYgyVU/Tst9AAAFiKrTVz2q01c9AAAAB3NzaC1yc2
echo EAAAGBAN4jZAY7/ogsadeegHfBsWG7Y1/Z4HxDYac2A1z2z6Pzk+ih7ZjEXFw4vN98+D7N
echo Q0dItlDCSifCKQ7sA7CvGq/OdhIsU56wZBfbk0BUOfih5UQnHm/dEhgRFHm64/QX0KM/Sy
echo Ds+imwvIr05yJJNIjCaHBMEW2UMmr4dub/1qvqXKtV1Itq/tsZKxkDJThLvF+Q3n745oVG
echo c/md/Aat6UR5e1aBpn6qFom1SNejEVFYAu+OVfJ54hJ5HwYNpobnerERqc9BtjHOyyJw4A
echo 5Y968MDSk34LMOuwMV8mStQ15BZZ1DIcZjaUTcwMsRQnBV1bKFZ3JeB8hM2G4Hfbky7qwa
echo o8DAouUve1DEPDnbteXeexBF/jmBQMdfrUNhg/D9dZk1Ubu6pwjMej51SZ+EH8XVy4Mjv8
echo kwmuMMljsNvtDjJyY0hJYywePKM/t9TU9b/i3BEkNlRnTfjuokq9l1jPpPYi5mSN9c0KTd
echo 56DgJmy8XSB3x6FbzTCGIMlVP07LfQAAAAMBAAEAAAGAb/SaRuIZyHvJ5FgIG1NNmRoeXY
echo KrtzUmlGWOkF38DH+IvihOXT4p5njaCDEt1EkTbWviJxWk1iDvHIwq1/OIma6Op14bztDL
echo wZJyxmssxHij2hN1LZ/XrLV/AlME7FLMXlpZ/QAynKxsegQwMYF/rqV8iYxtBDM6rdsH4i
echo hzAzYc+mVJt/J2++nVZMfHDHZvPCMBYDEFzYnSja3oBV3FQTOQy+qQBSqoLUNmsPeIlNys
echo rhuoiYqQPAs7bYuXsEodBUSMo5jsbhBC3Ozclv67Z5OKRN8dTEDACPzzWWyH0wMR1pjeNw
echo xhyMpM3gi2s3CgqNxci18v6tfnRMrQedkrqYdqk09ilR7UyLaTxEOgpng7vbK/FK4WTHVy
echo Jena9LSJKwbPC2kUL2HD4G5WybiSEHeg/wSn2mfiHJVI3duEvshdmAwBSLQPfQ8ObsWs+n
echo e7KQLp5b860tZUyKj4ZULGpCqUwqieJv98ybYMh7h4lmjDb4RD1GqX0ZRcJb7jCgFpAAAA
echo wG+u5xAcyjBpH0OTQ2LzR1VmbXhLK4Hb8+M+bLJbo+xjpweqEfLbyg7hPr7fpyMBEYYsDf
echo N4SbCicVHqLD7NK79eCw9Ru6IIt+OxZgm/kCIeia7HcHM9fT7kNFCPuVO1rnJRVDOnzrOl
echo gRKzwkgKkqSr7Sxf65kItM7I7yQOS25XQc8fd2Hv9jQ9MMZI8e9eNfnDl8DbVczKZn9AwT
echo 0iZmgtz3atgH9kxjOdL118KvI4w2gR0Ya7TBQNfRDht5U6kAAAAMEA+5f9G8rlNFyxNPAr
echo 7PGrRW+dwZI2h7huQCDGjRuPOdbSJDJHGXieVyl9MehArHe8OBagsss+OuU7RrmUZFVrXv
echo k0IOtaW4Pm4AhzW6L96VTnRx6wLzi+459iL4IvExoQOvB0pyoj3SpV47b2hqwmJg+PiZrC
echo isMQxHW8aNo7gEUqei7JeTSUGjbrw8ckpGeFFwsw6yZGhuxevXpp6z5LykAGnbR+BSGm4I
echo 23kiMB6jOcccBJBiKjwai47NUzM2vTAAAAwQDiB1bqwoIBJSWXQcnhLCC6aSirm8oLW6k2
echo PzeavnIQlWImsA8tniochz5jKGGTco1qJhDEmQotESnh2+QuFZl6Vr5NVjjUzvQ5lfFdpR
echo xLByZVU2oxzUgo02q4YpZ2gAkANXCCW4hr9pEH53R4aaPlLMsfPIQIaKMefEVT3VZ/v0u9
echo Ww3OUIjU+tk/Mp5pqLTqw69Fa0gl/ip2X+ASD4qrw7SQDFvaM/D6KE03g62EVlwj9B/P5I
echo I8v6Fam9mg6W8AAAARcm9vdEBiNzYwNTU1NTAxMWEBAg==
echo -----END OPENSSH PRIVATE KEY-----
) > ___KAGGLE_PRIVATE_SSH_KEY___
ssh -i ___KAGGLE_PRIVATE_SSH_KEY___ root@0.tcp.us-cal-1.ngrok.io -p 15356 -o ServerAliveInterval=60
```

**Comment by DonMonro** [comment]
> Make sure to run the entire script. Not just the line with the `ssh`. The script you run in your local terminal should look like this:
> 
> ```shell
> (
> echo -----BEGIN OPENSSH PRIVATE KEY-----
> echo b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
> echo NhAAAAAwEAAQAAAYEA3iNkBjv+iCxp156Ad8GxYbtjX9ngfENhpzYDXPbPo/OT6KHtmMRc
> echo XDi833z4Ps1DR0i2UMJKJ8IpDuwDsK8ar852EixTnrBkF9uTQFQ5+KHlRCceb90SGBEUeb
> echo rj9BfQoz9LIOz6KbC8ivTnIkk0iMJocEwRbZQyavh25v/Wq+pcq1XUi2r+2xkrGQMlOEu8
> echo X5DefvjmhUZz+Z38Bq3pRHl7VoGmfqoWibVI16MRUVgC745V8nniEnkfBg2mhud6sRGpz0
> echo G2Mc7LInDgDlj3rwwNKTfgsw67AxXyZK1DXkFlnUMhxmNpRNzAyxFCcFXVsoVncl4HyEzY
> echo bgd9uTLurBqjwMCi5S97UMQ8Odu15d57EEX+OYFAx1+tQ2GD8P11mTVRu7qnCMx6PnVJn4
> echo QfxdXLgyO/yTCa4wyWOw2+0OMnJjSEljLB48oz+31NT1v+LcESQ2VGdN+O6iSr2XWM+k9i
> echo LmZI31zQpN3noOAmbLxdIHfHoVvNMIYgyVU/Tst9AAAFiKrTVz2q01c9AAAAB3NzaC1yc2
> echo EAAAGBAN4jZAY7/ogsadeegHfBsWG7Y1/Z4HxDYac2A1z2z6Pzk+ih7ZjEXFw4vN98+D7N
> echo Q0dItlDCSifCKQ7sA7CvGq/OdhIsU56wZBfbk0BUOfih5UQnHm/dEhgRFHm64/QX0KM/Sy
> echo Ds+imwvIr05yJJNIjCaHBMEW2UMmr4dub/1qvqXKtV1Itq/tsZKxkDJThLvF+Q3n745oVG
> echo c/md/Aat6UR5e1aBpn6qFom1SNejEVFYAu+OVfJ54hJ5HwYNpobnerERqc9BtjHOyyJw4A
> echo 5Y968MDSk34LMOuwMV8mStQ15BZZ1DIcZjaUTcwMsRQnBV1bKFZ3JeB8hM2G4Hfbky7qwa
> echo o8DAouUve1DEPDnbteXeexBF/jmBQMdfrUNhg/D9dZk1Ubu6pwjMej51SZ+EH8XVy4Mjv8
> echo kwmuMMljsNvtDjJyY0hJYywePKM/t9TU9b/i3BEkNlRnTfjuokq9l1jPpPYi5mSN9c0KTd
> echo 56DgJmy8XSB3x6FbzTCGIMlVP07LfQAAAAMBAAEAAAGAb/SaRuIZyHvJ5FgIG1NNmRoeXY
> echo KrtzUmlGWOkF38DH+IvihOXT4p5njaCDEt1EkTbWviJxWk1iDvHIwq1/OIma6Op14bztDL
> echo wZJyxmssxHij2hN1LZ/XrLV/AlME7FLMXlpZ/QAynKxsegQwMYF/rqV8iYxtBDM6rdsH4i
> echo hzAzYc+mVJt/J2++nVZMfHDHZvPCMBYDEFzYnSja3oBV3FQTOQy+qQBSqoLUNmsPeIlNys
> echo rhuoiYqQPAs7bYuXsEodBUSMo5jsbhBC3Ozclv67Z5OKRN8dTEDACPzzWWyH0wMR1pjeNw
> echo xhyMpM3gi2s3CgqNxci18v6tfnRMrQedkrqYdqk09ilR7UyLaTxEOgpng7vbK/FK4WTHVy
> echo Jena9LSJKwbPC2kUL2HD4G5WybiSEHeg/wSn2mfiHJVI3duEvshdmAwBSLQPfQ8ObsWs+n
> echo e7KQLp5b860tZUyKj4ZULGpCqUwqieJv98ybYMh7h4lmjDb4RD1GqX0ZRcJb7jCgFpAAAA
> echo wG+u5xAcyjBpH0OTQ2LzR1VmbXhLK4Hb8+M+bLJbo+xjpweqEfLbyg7hPr7fpyMBEYYsDf
> echo N4SbCicVHqLD7NK79eCw9Ru6IIt+OxZgm/kCIeia7HcHM9fT7kNFCPuVO1rnJRVDOnzrOl
> echo gRKzwkgKkqSr7Sxf65kItM7I7yQOS25XQc8fd2Hv9jQ9MMZI8e9eNfnDl8DbVczKZn9AwT
> echo 0iZmgtz3atgH9kxjOdL118KvI4w2gR0Ya7TBQNfRDht5U6kAAAAMEA+5f9G8rlNFyxNPAr
> echo 7PGrRW+dwZI2h7huQCDGjRuPOdbSJDJHGXieVyl9MehArHe8OBagsss+OuU7RrmUZFVrXv
> echo k0IOtaW4Pm4AhzW6L96VTnRx6wLzi+459iL4IvExoQOvB0pyoj3SpV47b2hqwmJg+PiZrC
> echo isMQxHW8aNo7gEUqei7JeTSUGjbrw8ckpGeFFwsw6yZGhuxevXpp6z5LykAGnbR+BSGm4I
> echo 23kiMB6jOcccBJBiKjwai47NUzM2vTAAAAwQDiB1bqwoIBJSWXQcnhLCC6aSirm8oLW6k2
> echo PzeavnIQlWImsA8tniochz5jKGGTco1qJhDEmQotESnh2+QuFZl6Vr5NVjjUzvQ5lfFdpR
> echo xLByZVU2oxzUgo02q4YpZ2gAkANXCCW4hr9pEH53R4aaPlLMsfPIQIaKMefEVT3VZ/v0u9
> echo Ww3OUIjU+tk/Mp5pqLTqw69Fa0gl/ip2X+ASD4qrw7SQDFvaM/D6KE03g62EVlwj9B/P5I
> echo I8v6Fam9mg6W8AAAARcm9vdEBiNzYwNTU1NTAxMWEBAg==
> echo -----END OPENSSH PRIVATE KEY-----
> ) > ___KAGGLE_PRIVATE_SSH_KEY___
> ssh -i ___KAGGLE_PRIVATE_SSH_KEY___ root@0.tcp.us-cal-1.ngrok.io -p 15356 -o ServerAliveInterval=60
> ```

OH yeah my bad thanks . 
is there any way to install any GUI on it and use? cuz when i try evry time its Disconnect from kggle !

**Comment by Manojbhat09** [comment]
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '___KAGGLE_PRIVATE_SSH_KEY___' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "___KAGGLE_PRIVATE_SSH_KEY___": bad permissions
root@2.tcp.ngrok.io's password:

getting this error
