### ISSUE TITLE
GUI possible ?

### ISSUE THREAD

**Issue by DonMonro** [slooi/kaggle-ssh#2]
OK, I install XFCE Desktop Environment GUI for this but can I use this like RDP ? connect to that or some thing ?
cuz when I try connect Kaggle stop notebook and make it DC !!!

**Comment by slooi** [comment]
Unfortunately that's outside my knowledge as I only really ssh into my remote linux machines. Additionally, after I helped you with the previous issue my ngrok account got suspended so I kinda lost my means to test it 😅
