### ISSUE TITLE
unable to connect, REMOTE HOST IDENTIFICATION HAS CHANGED

### ISSUE THREAD

**Issue by 2575044704** [slooi/kaggle-ssh#3]
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!      Someone could be eavesdropping on you right now (man-in-the-middle attack)!                                           It is also possible that a host key has just been changed. The fingerprint for the ED25519 key sent by the remote host is                                                        SHA256:5hbPCKtRO176Epm633EgpJP2Du2Akvi0huui0/AN7wI.        Please contact your system administrator.                  Add correct host key in /data/data/com.termux/files/home/.ssh/known_hosts to get rid of this message.                 Offending ECDSA key in /data/data/com.termux/files/home/.ssh/known_hosts:10                                           Host key for [148.135.90.40]:12479 has changed and you have requested strict checking.                                Host key verification failed.

**Comment by slooi** [comment]
Not sure why or how you got that error. But I just tested the script and it works fine.

**Comment by 2575044704** [comment]
I successfully connected by removing ~/.ssh files
